const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const nodemailer = require('nodemailer');
const SOS = require('./models/SOS');
const Supply = require('./models/Supply');
const { calculatePriority } = require('./utils/priorityEngine');

const app = express();
app.use(cors());

// Increase JSON limit to handle large Base64 PDF strings from the frontend
app.use(express.json({ limit: '50mb' }));
app.use(express.urlencoded({ limit: '50mb', extended: true }));

mongoose.connect('mongodb://127.0.0.1:27017/resilinet')
  .then(() => console.log("Connected to MongoDB successfully"))
  .catch(err => console.error("Database Connection Error:", err));

// --- NODEMAILER CONFIGURATION ---
const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: 'jhamarpit@gmail.com', 
        pass: 'hypasgtsmnxkhyer' // Integrated your App Password
    }
});

// GET: Fetch all active alerts with priority scoring
app.get('/api/alerts', async (req, res) => {
    try {
        const alerts = await SOS.find({ status: 'Active' });
        const smartAlerts = await Promise.all(alerts.map(async (alert) => {
            const clusterCount = await SOS.countDocuments({
                _id: { $ne: alert._id },
                status: 'Active',
                location: {
                    $geoWithin: {
                        $centerSphere: [
                            [alert.location.coordinates[0], alert.location.coordinates[1]], 
                            0.1 / 6378.1 
                        ]
                    }
                }
            });
            return {
                ...alert._doc,
                priorityScore: calculatePriority(alert, clusterCount)
            };
        }));
        res.json(smartAlerts.sort((a, b) => b.priorityScore - a.priorityScore));
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// POST: Dispatch PDF Report to Authorities
app.post('/api/dispatch-report', async (req, res) => {
    const { pdfBase64, recipientEmail } = req.body;
    try {
        const mailOptions = {
            from: '"ResiliNet Intel Hub" <jhamarpit@gmail.com>',
            to: recipientEmail,
            subject: `🚨 EMERGENCY INTEL REPORT: ${new Date().toLocaleDateString()}`,
            text: "Attention: This is an automated disaster intelligence report generated by ResiliNet. Please find the attached PDF containing incident distributions and predictive risk hotspots.",
            attachments: [{
                filename: `ResiliNet_Intel_Report_${Date.now()}.pdf`,
                content: pdfBase64.split("base64,")[1],
                encoding: 'base64'
            }]
        };

        await transporter.sendMail(mailOptions);
        res.json({ success: true, message: "Report dispatched to authorities successfully." });
    } catch (err) {
        console.error("Email Dispatch Error:", err);
        res.status(500).json({ error: "Failed to dispatch email. Verify App Password." });
    }
});

// GET: Weekly Analytics
app.get('/api/analytics/weekly', async (req, res) => {
    try {
        const sevenDaysAgo = new Date();
        sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);
        const stats = await SOS.aggregate([
            { $match: { timestamp: { $gte: sevenDaysAgo } } },
            { $group: { _id: "$category", count: { $sum: 1 } } }
        ]);
        res.json(stats);
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// POST: Create a new SOS Alert (Mobile)
app.post('/api/sos', async (req, res) => {
    try {
        const { name, phone, message, location, category, ai_insight } = req.body;
        const newSOS = new SOS({
            name, phone, message, category, ai_insight,
            location: { type: 'Point', coordinates: [location.longitude, location.latitude] },
            status: 'Active'
        });
        await newSOS.save();
        res.status(201).json({ success: true });
    } catch (err) {
        res.status(500).json({ error: "Failed to process SOS signal." });
    }
});

// PUT: Resolve SOS
app.put('/api/sos/resolve/:id', async (req, res) => {
    try {
        await SOS.findByIdAndUpdate(req.params.id, { status: 'Resolved' });
        res.json({ success: true });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

const PORT = 5000;
app.listen(PORT, '0.0.0.0', () => {
    console.log(`ResiliNet Core Hub active on port ${PORT}`);
});
// Add this route near your other SOS routes in server.js

// DANGER ZONE: Wipe all SOS data
app.delete('/api/danger/wipe-all', async (req, res) => {
    try {
        await SOS.deleteMany({});
        res.json({ success: true, message: "All alerts have been wiped." });
    } catch (err) {
        res.status(500).json({ error: "Failed to clear database." });
    }
});